/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.hallock.dota.view;

import org.hallock.dota.control.Registry;
import org.hallock.dota.model.Identifications;

import java.util.LinkedList;

/**
 *
 * @author thallock
 */
public class DebugPane extends javax.swing.JPanel implements Ui.View {

    Identifications.IdentificationResults results;
    /**
     * Creates new form DebugPane
     */
    public DebugPane() {
        initComponents();
    }
    
    public void setResults(Identifications.IdentificationResults results) {
        this.results = results;
    }

    private String toDisplay(LinkedList<Integer> list) {
        if (list.isEmpty()) {
            return "empty";
        }
        LinkedList<String> heroes = new LinkedList<>();
        for (Integer pickId : list) {
            heroes.add(Registry.getInstance().heroes.getHeroByPickId(pickId).display);
        }
        return String.join(", ", heroes.toArray(new String[0]));
    }
    
    public void refresh() {
        direBansLabel.setText(results == null ? "loading..." : toDisplay(results.banned));
        direPicksLabel.setText(results == null ? "loading..." : toDisplay(results.direPicked));
        radiantPicksLabel.setText(results == null ? "loading..." : toDisplay(results.radiantPicked));
        isRadiantLabel.setText(results == null ? "loading..." : String.valueOf(results.playerIsRadiant));
        radiantBansLabel.setText("not supported yet.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        radiantPicksLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        direPicksLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        isRadiantLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        radiantBansLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        direBansLabel = new javax.swing.JLabel();

        jLabel1.setText("Radiant Picks:");

        radiantPicksLabel.setText("loading...");

        jLabel3.setText("Dire Picks:");

        direPicksLabel.setText("loading....");

        jLabel5.setText("Player is Radiant:");

        isRadiantLabel.setText("loading...");

        jLabel7.setText("Radiant Bans:");

        radiantBansLabel.setText("loading...");

        jLabel9.setText("Dire Bans:");

        direBansLabel.setText("loading...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(direBansLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(radiantBansLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(isRadiantLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(direPicksLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(radiantPicksLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radiantPicksLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(direPicksLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(isRadiantLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radiantBansLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(direBansLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel direBansLabel;
    private javax.swing.JLabel direPicksLabel;
    private javax.swing.JLabel isRadiantLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel radiantBansLabel;
    private javax.swing.JLabel radiantPicksLabel;
    // End of variables declaration//GEN-END:variables
}
