/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.hallock.dota.view;

import org.hallock.dota.control.Registry;
import org.hallock.dota.model.geometry.HeroGridGeometry;
import org.hallock.dota.view.Ui.View;
import org.json.JSONException;

import java.io.IOException;

/**
 *
 * @author thallock
 */
public class GridConfig extends javax.swing.JPanel implements View {

    /**
     * Creates new form GridConfig
     */
    public GridConfig() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        hGapSpinner = new javax.swing.JSpinner();
        vGapSpinner = new javax.swing.JSpinner();
        vTypeGapSpinner = new javax.swing.JSpinner();
        heightSpinner = new javax.swing.JSpinner();
        widthSpinner = new javax.swing.JSpinner();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        startXSpinner = new javax.swing.JSpinner();
        startYSpinner = new javax.swing.JSpinner();

        jLabel1.setText("Hero width:");

        jLabel2.setText("Hero height:");

        jLabel3.setText("Horizontal gap:");

        jLabel4.setText("Vertical gap:");

        jLabel5.setText("Vertical gap between types:");

        hGapSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        hGapSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                hGapSpinnerStateChanged(evt);
            }
        });

        vGapSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        vGapSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                vGapSpinnerStateChanged(evt);
            }
        });

        vTypeGapSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        vTypeGapSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                vTypeGapSpinnerStateChanged(evt);
            }
        });

        heightSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        heightSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                heightSpinnerStateChanged(evt);
            }
        });

        widthSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        widthSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                widthSpinnerStateChanged(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Start x:");

        jLabel7.setText("Start y:");

        startXSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        startXSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                startXSpinnerStateChanged(evt);
            }
        });

        startYSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        startYSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                startYSpinnerStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vTypeGapSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(vGapSpinner)
                            .addComponent(hGapSpinner)
                            .addComponent(heightSpinner)
                            .addComponent(widthSpinner)
                            .addComponent(startYSpinner)
                            .addComponent(startXSpinner))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(widthSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(heightSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(hGapSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(vGapSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(vTypeGapSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(startXSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(startYSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        Registry.getInstance().ui.hide(Ui.GRID_CONFIG_VIEW);
        Registry.getInstance().ui.hide(Ui.GRID_PREVIEW);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void widthSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_widthSpinnerStateChanged
        refreshPreview();
    }//GEN-LAST:event_widthSpinnerStateChanged

    private void heightSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_heightSpinnerStateChanged
        refreshPreview();
    }//GEN-LAST:event_heightSpinnerStateChanged

    private void hGapSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_hGapSpinnerStateChanged
        refreshPreview();
    }//GEN-LAST:event_hGapSpinnerStateChanged

    private void vGapSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_vGapSpinnerStateChanged
        refreshPreview();
    }//GEN-LAST:event_vGapSpinnerStateChanged

    private void vTypeGapSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_vTypeGapSpinnerStateChanged
        refreshPreview();
    }//GEN-LAST:event_vTypeGapSpinnerStateChanged

    private void startXSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_startXSpinnerStateChanged
        refreshPreview();
    }//GEN-LAST:event_startXSpinnerStateChanged

    private void startYSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_startYSpinnerStateChanged
        refreshPreview();
    }//GEN-LAST:event_startYSpinnerStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JSpinner hGapSpinner;
    private javax.swing.JSpinner heightSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton saveButton;
    private javax.swing.JSpinner startXSpinner;
    private javax.swing.JSpinner startYSpinner;
    private javax.swing.JSpinner vGapSpinner;
    private javax.swing.JSpinner vTypeGapSpinner;
    private javax.swing.JSpinner widthSpinner;
    // End of variables declaration//GEN-END:variables

    @Override
    public void refresh() {
        HeroGridGeometry gridGeometry = Registry.getInstance().gridGeometry;
        startXSpinner.setValue(gridGeometry.heroStartX);
        startYSpinner.setValue(gridGeometry.heroStartY);
        vGapSpinner.setValue(gridGeometry.heroVerticalGap);
        vTypeGapSpinner.setValue(gridGeometry.heroTypeGap);
        widthSpinner.setValue(gridGeometry.heroWidth);
        hGapSpinner.setValue(gridGeometry.heroHorizontalGap);
        heightSpinner.setValue(gridGeometry.heroHeight);
        refreshPreview();
    }
    
    public void refreshPreview() {
        // Registry.getInstance().ui.show(Ui.GRID_PREVIEW);
        GridPreviewer preview = (GridPreviewer) Registry.getInstance().ui.getView(Ui.GRID_PREVIEW).panel;
        try {
            preview.drawGrid(getGeometry());
        } catch (JSONException e) {
            Registry.getInstance().logger.log("Unable to show geometry", e);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    public HeroGridGeometry getGeometry() {
        HeroGridGeometry gridGeometry = new HeroGridGeometry();
        gridGeometry.heroStartX = (Integer) startXSpinner.getValue();
        gridGeometry.heroStartY = (Integer) startYSpinner.getValue();
        gridGeometry.heroTypeGap = (Integer) vTypeGapSpinner.getValue();
        gridGeometry.heroVerticalGap = (Integer) vGapSpinner.getValue();
        gridGeometry.heroWidth = (Integer) widthSpinner.getValue();
        gridGeometry.heroHorizontalGap = (Integer) hGapSpinner.getValue();
        gridGeometry.heroHeight = (Integer) heightSpinner.getValue();
        return gridGeometry;
    }
}
